name: Tests

# CINTENT >> MANUAL_TRIGGER
# on: 
#   push:
#     paths:
#       - '.github/workflows/tests.yml'
#       - 'deepface/**'  
#       - 'tests/**'
#       - 'api/**'
#       - 'requirements.txt'
#       - '.gitignore'
#       - 'setup.py'
#   pull_request:
#     paths:
#       - '.github/workflows/tests.yml'
#       - 'deepface/**'  
#       - 'tests/**'
#       - 'api/**'
#       - 'requirements.txt'
#       - '.gitignore'
#       - 'setup.py'
on: [repository_dispatch, workflow_dispatch]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # sending files in form data throwing error in flask 3 while running tests
        pip install Werkzeug==2.0.2 flask==2.0.2
        pip install .
        
    - name: Test with pytest
      run: |
        cd tests
        python -m pytest . -s --disable-warnings

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}

  linting:
    needs: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==3.0.2
        pip install black
        pip install .
        
    - name: Lint with pylint
      run: |
        pylint --fail-under=10 deepface/

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}
